# Generated by Django 4.2.9 on 2024-02-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('private', 'private'), ('group', 'group')], max_length=8, null=True),
        ),
    ]
