# Generated by Django 5.0.2 on 2024-02-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_chatrequest_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
