# Generated by Django 5.0.2 on 2024-02-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_chatrequest_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrequest',
            name='title',
        ),
    ]
