# Generated by Django 5.0.1 on 2024-05-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_favouriteuser_event_id_favouriteuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriteuser',
            name='status',
        ),
    ]
