# Generated by Django 5.0.1 on 2024-05-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_favouriteuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteuser',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
