# Generated by Django 4.2.9 on 2024-02-14 06:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_rename_likeevent_eventlike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='adult_price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='children_price',
        ),
        migrations.RemoveField(
            model_name='event',
            name='early_bird_price',
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ticket', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.event')),
            ],
            options={
                'db_table': 'event_tickets',
                'indexes': [models.Index(fields=['uuid'], name='event_ticke_uuid_0ee459_idx')],
            },
        ),
    ]
