# Generated by Django 4.2.9 on 2024-02-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_remove_event_adult_price_remove_event_children_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
