# Generated by Django 4.2.9 on 2024-02-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_eventticket_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventticket',
            old_name='ticket',
            new_name='price',
        ),
    ]
