# Generated by Django 4.2.9 on 2024-02-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_rename_ticket_eventticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='currency',
            field=models.CharField(blank=True, default='$', max_length=10, null=True),
        ),
    ]
