# Generated by Django 4.2.9 on 2024-02-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_eventticket_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='left',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventticket',
            name='unit',
            field=models.IntegerField(null=True),
        ),
    ]
