# Generated by Django 4.2.9 on 2024-02-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_eventticket_left_eventticket_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventticket',
            old_name='unit',
            new_name='units',
        ),
    ]
