# Generated by Django 4.2.9 on 2024-02-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_rename_unit_eventticket_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
