# Generated by Django 4.2.9 on 2024-02-20 11:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_club_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventticket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='eventticket',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='eventticket',
            name='left',
        ),
        migrations.RemoveField(
            model_name='eventticket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='eventticket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='eventticket',
            name='units',
        ),
        migrations.RemoveField(
            model_name='eventticket',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='eventticket',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.event'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('price', models.FloatField(null=True)),
                ('currency', models.CharField(blank=True, default='$', max_length=10, null=True)),
                ('left', models.IntegerField(null=True)),
                ('units', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'tickets',
                'indexes': [models.Index(fields=['uuid'], name='tickets_uuid_13b7b5_idx')],
            },
        ),
        migrations.AddField(
            model_name='eventticket',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.ticket'),
        ),
    ]
