# Generated by Django 4.2.9 on 2024-03-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_event_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
