# Generated by Django 4.2.9 on 2024-02-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='type',
        ),
    ]
