# Generated by Django 4.2.9 on 2024-02-21 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_remove_eventticket_created_at_and_more'),
        ('order', '0005_orderitem_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.ticket'),
        ),
    ]
