# Generated by Django 4.2.9 on 2024-02-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderitem_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed'), ('refunded', 'refunded')], default='completed', max_length=15),
        ),
    ]
