# Generated by Django 4.2.11 on 2024-03-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_order_status_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('verified', 'verified'), ('not verified', 'not verified'), ('expired', 'expired')], default='valid', max_length=15),
        ),
    ]
