# Generated by Django 4.2.9 on 2024-03-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_scanned',
            field=models.BooleanField(default=False),
        ),
    ]
