# Generated by Django 5.0.4 on 2024-05-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_orderitem_is_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('free', 'free')], default='null', max_length=15, null=True),
        ),
    ]
