# Generated by Django 5.0.4 on 2024-05-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('free', 'free')], default=None, max_length=15, null=True),
        ),
    ]
